### ISSUE TITLE
Release an updated tag

### ISSUE THREAD

**Issue by MovieStoreGuy** [DataDog/sketches-go#40]
**Describe what happened:**
I am looking to play with some of the functions in master however they are not part of the most recent tag as seen by this diff https://github.com/DataDog/sketches-go/compare/v1.0.0...master

**Describe what you expected:**
I would expect that any significant changes would also come with a new tagged release for others to consume within their applications.

**Steps to reproduce the issue:**
No real steps just sadness when looking to use the functions in master but unable to due to semconv imports.

**Comment by CharlesMasson** [comment]
We just released https://github.com/DataDog/sketches-go/releases/tag/v2.0.0. Closing this issue, but please let me know if there still is an issue.
