### ISSUE TITLE
[feature request] Serialization & Weighted Values

### ISSUE THREAD

**Issue by okayzed** [DataDog/sketches-go#8]
Two useful features for histograms are adding weighted values and the ability to serialize the sketch to and from bytes. Please consider adding these to DDSketch. I will attempt to add them in my own local fork of ddsketch as well. 

The signature for adding weighted values is: ```addWeightedValue(val, count)```

**Comment by jeerim** [comment]
Thanks for the suggestions. The sketches can now be serialized with protobuf, and weighted values can be added via `AddWithCount(value, count)`.
